### ISSUE TITLE
AngleSharp.Scripting, AngleSharp.Io. No support for dotNet Framework 4?

### ISSUE THREAD

**Issue by skr4tchGr3azyMonkiBallllllZzzz** [AngleSharp/AngleSharp.Js#25]
I tried to install "AngleSharp.Scripting" & "AngleSharp.Io" using Nuget. Both packages failed to install and get referenced.

"AngleSharp" has support for target framework net40 but not "AngleSharp.Scripting" & "AngleSharp.Io" ?

**Comment by FlorianRappl** [comment]
Yes, this is true. This may change once I find the time to continue development on the AngleSharp plugins, which would involve .NET core and finer grained dependencies. I think .NET 4 should be possible with a reference to the Bcl.Async. You may compile from source and reference it manually.

I keep the issue open to remind me on the enhancement.

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Thanks a lot for the quick reply. I'm very much interested in the scripting functionality where we can inject JS, query variables, invoke functions, pass objects, run script/eval (like from a browser console) and get returns.

I will try compiling from the source. Thank you for the help.

**Comment by FlorianRappl** [comment]
I should have some time to continue working on this soon. In the meantime any help is appreciated.

**Comment by Rast1234** [comment]
Hello. I was unable to install this package from nuget, because it does not support .NET Core, looks like it's kind of similar issue. I compiled it from sources with VS2017 targeting `netstandard1.6`. I had to reference `System.Net.NetworkInformation.dll` and edit `/src/AngleSharp.Scripting.JavaScript/SystemTypeConverter.cs` a bit. If you want, i can share my diff via pull request so you will have less issues if you want to target .NET Core in future.

**Comment by FlorianRappl** [comment]
Sure, go ahead!

**Comment by Rast1234** [comment]
Nevermind, it crashes in runtime :( After some time trying to figure out how to overcome it, i switched to full .NET Framework. Also, the need to reference `System.Net.NetworkInformation.dll` just to compile it ruins the whole idea of using .NET Core.

**Comment by FlorianRappl** [comment]
Yup. In general it should run, but besides the one you mentioned the external dependency to Jint is the most crucial part. Here only the latest version is ready for .NET Standard / .NET Core. I am uncertain about the required changes in AS Scripting to make it work yet.

**Comment by FlorianRappl** [comment]
This is obsolete now. With AngleSharp now being .NET Standard 2.0 (or 1.3 incoming) there is no chance of having this in .NET 4.

Also Jint 3 (which will be used for AngleSharp.Js) is at least on .NET Standard 2.0.
