### ISSUE TITLE
How to execute Javascript with anchor tag to submit a form?

### ISSUE THREAD

**Issue by sohaibameen** [AngleSharp/AngleSharp.Js#47]
Hi, 

I have a page where multiple links are present with a form attached to every link. 

><td class="details"><a class="line" href="javascript:document.details0.submit();">details</a>
                    <form class="block" id="details0" name="details0" action="/Details" method="post">
                        <input type="hidden" id="stampal" name="stampal" value="S029W151921782129800000">
                        <input type="hidden" id="sentBy" name="sentBy" value="S029W">
                        <input type="hidden" id="page" name="page" value="Detail">
                    </form>
 </td>

On clicking anchor tag it executes Javascript code "javascript:document.details0.submit();" and submits the form to take the user to detail page. 

I have two requirements for this
 
1- how can I execute Javascript in given link to submit form? 
2- How can I get the current detail form's context to scrap the information? 

Best Regards, 
Sohaib

**Comment by FlorianRappl** [comment]
Landed in `devel`.
