### ISSUE TITLE
Implict wait for content to load

### ISSUE THREAD

**Issue by s0thl** [AngleSharp/AngleSharp.Js#57]
I just have discovered AngleSharp and I'm trying to learn about it.

I want to use it for testing my website, where content is dynamically generated.

Currently during loading, AngleSharp loads a document with the load spinner and not the actual loaded, ready document.

How can I implicitly wait during `OpenAsync` task for the element in the document to be loaded and visible?

**Comment by FlorianRappl** [comment]
Reopen for the `WaitUntil...` helper methods and additional documentation.

Also for potential enhancements / bug reports on that / similar topics.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
