### ISSUE TITLE
.NetStandard1.3 Support

### ISSUE THREAD

**Issue by TFarleyAZ** [AngleSharp/AngleSharp.Js#58]
### Description

AngleSharp supports .NetStandard 1.3 ,  .NetStandard 2.0, and .NetFramework 4.6 . Will the JS, Css, Io, etc.. extensions also have .NetStandard1.3 support? 

### Background

I use Net Core 1.1 and wanted to use AngleSharp, but I need the extensions and none of them support .NetStandard1.3. I attempted using AngleSharp 0.9.9 with AngleSharp.Scripting.Javascript, but does not appear to work with my JQuery version and other packages that use JQuery.

### Specification

AngleSharp 0.12.1
AngleSharp.Js 0.12.1
AngleSharp.Io 0.12.1
AngleSharp.Css 0.12.1

**Comment by FlorianRappl** [comment]
AngleSharp.Js depends a lot of reflection which may not be (API-wise) available in the desired / lower-range API sets (I think some of the required APIs are not there - but please check yourself).

Furthermore, AngleSharp.Js introduces a dependency to Jint, which means we are always bound to this dependency with the lowest supported .NET Standard (afaik right now this just fulfills .NET Standard 1.3).

Regarding jQuery - depending on the version of jQuery this is / was not working. In general, jQuery (or any "advanced" JS library) is currently out of scope. It is our goal to support all these libraries, but much work needs to be done to understand what (mostly drawing) APIs to "mock" and how to perfectly tune the event loop to make all these interactions work as expected. Hacking Jint a bit is also involved from time to time (and all libraries must not go beyond ES5).

HTH!

(I leave the issue open until I know for sure if we could potentially also release AngleSharp.Js as  .NET Standard 1.3 lib)

**Comment by FlorianRappl** [comment]
Landed in `devel`.
