### ISSUE TITLE
How get executed javascript

### ISSUE THREAD

**Issue by MHKarami97** [AngleSharp/AngleSharp.Js#67]
For example there is some code like this in some website:  

`<script>  
var test=12;  
var test1="num";  
var result = test + "/" + test1;  
</script>`

is there a way to get value of result after page loaded completely? 
in this code : "12/num"

**Comment by FlorianRappl** [comment]
If you have this script as-is on the page then, unfortunately, no.

It's like in a browser - you also cannot get the result of such an evaluation.

**Comment by MHKarami97** [comment]
@FlorianRappl 
Thanks, yes it's on page, I get and save it as string, is there way to parse that string as javascript to excute value?

**Comment by FlorianRappl** [comment]
From the README:

```cs
var numEntries = document.ExecuteScript("document.querySelectorAll('div').length");
```

Does that help?
