### ISSUE TITLE
How to execute simple Javascript?

### ISSUE THREAD

**Issue by BrianAllred** [AngleSharp/AngleSharp.Js#69]
I've got the document loaded and I only need to execute a single line of JS, but I can't find any trivial examples.

**Comment by FlorianRappl** [comment]
Not sure how this is a bug. For questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/anglesharp) or specify exactly what you tried and what failed.

The README shows a couple of ways how this can be used.

For instance, the following is contained in there, which looks like a match according to the given information:

```cs
var config = Configuration.Default.WithJs();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(address).WaitUntilAvailable();
var numEntries = document.ExecuteScript("document.querySelectorAll('div').length");
```

Hope that helps!
